name: âœ”Build Status Check


on:
  pull_request:
    types: [ synchronize ]
    paths:
      - ".github/**"
      - 'Documentation/**'
      - '.editorconfig'
      - '*.runsettings'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - '*.yml'
      - '.vscode/**'
      - '*.sln'
      - '*.csproj'


jobs:
  Build_Status_Check:
    name: Build Status Check
    runs-on: windows-latest
    steps:
    - name: Build Project
      run: 'Write-Host "No build required."'
