name: ðŸš€QA/Prod Release


env:
  PROJECT_NAME: Velaptor
  NET_SDK_VERSION: 5.0.x # Changing this means changing ARTIFACT_FOLDER_NAME
  ARTIFACT_FOLDER_NAME: '5.0' # Changing this means changing NET_SDK_VERSION


on:
  workflow_dispatch:
  push:
    branches: [
      develop, # QA Releases
      master # Production Releases
    ]
    paths-ignore:
      - ".github/**"
      - 'Documentation/**'
      - '.editorconfig'
      - '*.runsettings'
      - '.gitattributes'
      - '.gitignore'
      - '*.md'
      - '.vscode/**'


jobs:
  Validate_Version:
    name: Validate Version
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Version From Project File
      id: proj-file-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    # TODO: Remove this once the VersionValidator has its 'fail-if-contains' feature is implemented
    - name: Validate Version Type
      run: |
        $projFileVersion = "${{ steps.proj-file-version.outputs.version }}";

        # Fail if the version is not a preview type and this is a production release
        if ($projFileVersion.Contains("-preview.") -and "${{ github.ref }}".EndsWith("master"))
        {
            echo "The version '${{ steps.proj-file-version.outputs.version }}' must not be a preview version type for QA and Production releases.";
            echo "Valid Version Example: v1.2.3";

            exit 1 # Fail
        }

    # TODO: Make use of new optional input 'fail-if-contains' for preview.3 of this action once it has been implemented
    - name: Validate Version
      uses: KinsonDigital/VersionValidator@v1.0.0-preview.2
      with:
        nuget-package-name: "KinsonDigital.Velaptor"
        version: "${{ steps.proj-file-version.outputs.version }}"
        check-nuget: "true"
        fail-if-nuget-version-exists: "true"
      

  Validate_Branch:
    name: Validate Branch
    runs-on: windows-latest
    steps:
    # TODO: Replace this with the new upcoming branch validation github action
    - name: Validate Branch Name
      run: |
        # If the branch is not a 'develop' or 'master' branch, fail the workflow
        if ("${{ github.ref }}".EndsWith("develop") -eq $false -and "${{ github.ref }}".EndsWith("master") -eq $false)
        {
          echo "QA releases can only be performed with the 'develop' branch."
          echo "Production releases can only be performed with the 'master' branch."
          exit 1 # Fail
        }


  Determine_Build_Config:
    name: Determine Build Config
    runs-on: windows-latest
    steps:
    - name: Determine Build Config
      id: determine_build_config
      run: |
        # If the branch ends with master, the build config is release
        if ("${{ github.ref }}".EndsWith("master")) {
          echo "::set-output name=build-config::Release"
        } else { # Build config for any other branch is debug
          echo "::set-output name=build-config::Debug"
        }
    outputs:
      build-config: ${{ steps.determine_build_config.outputs.build-config }}


  Validate_Release_Notes_Exist:
    name: Validate Release Notes Exist
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Version From Project File
      id: proj-file-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check For Release Notes
      run: |
        [string]$version = "${{ steps.proj-file-version.outputs.version }}";
        [string]$filePath = "${{ github.workspace }}\Documentation\ReleaseNotes\ProductionReleases\Release-Notes-v$version.md";
        
        if (-not([System.IO.File]::Exists($filePath))) {
          Write-Host "A production release notes file '$filePath' does not exist.";
          Write-Host "You must add release notes for production releases.";
        
          exit 1 # Fail
        }


  Build_And_Test_Library:
    name: Build & Test (Library)
    runs-on: windows-latest
    needs: [
      Validate_Version,
      Validate_Branch,
      Determine_Build_Config,
      Validate_Release_Notes_Exist
    ]
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NET_SDK_VERSION }}

    - name: Get Version From Project File
      id: proj-file-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Display Workflow Info
      run: |
        echo "Build Config: ${{ needs.Determine_Build_Config.outputs.build-config }}"
        echo "Current Branch: ${{ github.ref }}"
        echo "Project File Version: ${{ steps.proj-file-version.outputs.version }}"

    - name: Restore Dependencies
      run: dotnet restore "${{ github.workspace }}/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj"

    - name: Build
      run: dotnet build "${{ github.workspace }}/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj" `
        -c ${{ needs.Determine_Build_Config.outputs.build-config }} `
        --no-restore

    - name: Execute Unit Tests
      run: dotnet test "${{ github.workspace }}/Testing/${{ env.PROJECT_NAME }}Tests/${{ env.PROJECT_NAME }}Tests.csproj" `
        -c ${{ needs.Determine_Build_Config.outputs.build-config }} `
        --collect:"XPlat Code Coverage" `
        --no-restore

    - name: Publish Code Coverage Results
      uses: codecov/codecov-action@v1.5.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ${{ github.workspace }}/Testing/${{ env.PROJECT_NAME }}Tests/TestResults/**/coverage.cobertura.xml

    - name: Publish Build Artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: ${{ env.PROJECT_NAME }} Build Artifacts
        path: ${{ github.workspace }}/${{ env.PROJECT_NAME }}/bin/${{ needs.Determine_Build_Config.outputs.build-config }}/net${{ env.ARTIFACT_FOLDER_NAME }}
        error: There was an issue uploading the build artifact

    - name: Setup Nuget
      uses: NuGet/setup-nuget@v1.0.5

    - name: Create Nuget Package
      run: dotnet pack "${{ github.workspace }}/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj" `
        -o "${{ github.workspace }}" `
        -c ${{ needs.Determine_Build_Config.outputs.build-config }}
   
    - name: Publish Nuget Package
      if: endsWith(github.ref, 'master')
      run: echo "Publish Nuget Package Step Invoked"
      run: dotnet nuget push "${{ github.workspace }}/KinsonDigital.${{ env.PROJECT_NAME }}.${{ steps.proj-file-version.outputs.version }}.nupkg" `
        --api-key ${{ secrets.NUGET_ORG_API_KEY }} `
        --source https://api.nuget.org/v3/index.json


  Build_And_Release_Testing_App:
    name: Build & Release (Testing App)
    runs-on: windows-latest
    needs: [
      Validate_Version,
      Validate_Branch,
      Determine_Build_Config,
      Validate_Release_Notes_Exist ]
    steps:
    - uses: actions/checkout@v2

    - name: Get Version From Project File
      id: proj-file-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Release Type
      id: determine_release_type
      run: |
        echo "Branch: ${{ github.ref }}"

        # If the branch is master, then set the release type to production
        if ("${{ github.ref }}".EndsWith("master"))
        {
          echo "::set-output name=is-prerelease::false";
          echo "::set-output name=release-type::Production";
        }
        elseif ("${{ github.ref }}".EndsWith("develop"))
        { # If the branch is the develop branch, set the release type to qa
          echo "::set-output name=is-prerelease::true";
          echo "::set-output name=release-type::QA";
        }

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NET_SDK_VERSION }}

    - name: Restore Dependencies
      run: dotnet restore "${{ github.workspace }}/Testing/${{ env.PROJECT_NAME }}Testing/${{ env.PROJECT_NAME }}Testing.csproj"

    - name: Build Testing App
      run: |
        dotnet publish "${{ github.workspace }}/Testing/${{ env.PROJECT_NAME }}Testing/${{ env.PROJECT_NAME }}Testing.csproj" `
          -c ${{ needs.Determine_Build_Config.outputs.build-config }} `
          -o "${{ github.workspace }}/Testing/${{ steps.determine_release_type.outputs.release-type }}Release/" `
          --no-restore `

    - name: Package Testing App
      run: |
        Compress-Archive -Path "${{ github.workspace }}/Testing/${{ steps.determine_release_type.outputs.release-type }}Release" `
          -DestinationPath "${{ github.workspace }}/${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip" `
          -Force

    - name: Release Testing Application (QA)
      if: github.ref == 'develop'
      uses: softprops/action-gh-release@v0.1.12
      with:
        tag_name: v${{ steps.proj-file-version.outputs.version }}
        body: |
          ${{ env.PROJECT_NAME }} - ${{ steps.determine_release_type.outputs.release-type }} Release
          Execute the testing application in the **_${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip_** file to perform manual testing.
        files: ${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip
        prerelease: ${{ steps.determine_release_type.outputs.is-prerelease }}

    - name: Release Testing Application (Production)
      if: github.ref == 'master'
      uses: softprops/action-gh-release@v0.1.12
      with:
        tag_name: v${{ steps.proj-file-version.outputs.version }}
        body: |
          ${{ env.PROJECT_NAME }} - ${{ steps.determine_release_type.outputs.release-type }} Release
          Execute the testing application in the **_${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip_** file to perform manual testing.
        files: |
          ${{ env.PROJECT_NAME }}-TestingApp-v${{ steps.proj-file-version.outputs.version }}.zip
          ${{ github.workspace }}\Documentation\ReleaseNotes\ProductionReleases\Release-Notes-v${{ steps.proj-file-version.outputs.version }}.md
        prerelease: ${{ steps.determine_release_type.outputs.is-prerelease }}


  Broadcast_To_Social_Media:
    name: Broadcast To Social Media
    runs-on: windows-latest
    needs: [
      Validate_Version,
      Validate_Branch,
      Build_And_Test_Library,
      Build_And_Release_Testing_App
    ]
    steps:
    - name: Get Version From Project File
      id: proj-file-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Determine Tweet Broadcast
      id: determine_tweet_broadcast
      run: |
        if ("${{ secrets.TWITTER_BROADCAST_ENABLED }}" -eq "true" -and `
            "${{ github.ref }}".EndsWith("master")) {
          echo "::set-output name=broadcast-tweet::true";
        } else {
          echo "::set-output name=broadcast-tweet::false";
        }

    - name: Send Tweet About Release
      if: steps.determine_tweet_broadcast.outputs.broadcast-tweet == 'true'
      uses: ethomson/send-tweet-action@v1
      with:
        status: |
          ${{ env.PROJECT_NAME }} v'${{ steps.proj-file-version.outputs.version }}' just dropped!! ðŸš€
          Come check it out to take it for a spin and help support the projects. ðŸ¤˜
          Release: https://github.com/KinsonDigital/${{ env.PROJECT_NAME }}/releases/tag/${{ steps.proj-file-version.outputs.version }}
          Nuget Package: https://www.nuget.org/packages/KinsonDigital.${{ env.PROJECT_NAME }}/${{ steps.proj-file-version.outputs.version }}
          Project: https://github.com/KinsonDigital/${{ env.PROJECT_NAME }}
        consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
