name: Tag Does Not Exit Status Check

env:
  PROJECT_NAME: Velaptor

on:
  workflow_dispatch:
  pull_request:
    types: [ synchronize ]
    branches: [ release/v*.*.* ]

jobs:
  Tag_Does_Not_Exit_Status_Check:
    name: Tag Does Not Exit Status Check
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get Version From Project File
      id: get-version
      uses: KinsonDigital/vget@v0.4.0
      with:
        repo-owner-and-name: '${{ github.repository }}'
        branch: '${{ github.ref }}'
        relative-file-path: '${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check If Tag Exists
      id: tag-verifier
      uses: KinsonDigital/TagVerifier@v0.3.1
      with:
        repo-owner-and-name: '${{ github.repository }}'
        tag-name: '${{ steps.get-version.outputs.version }}'
        repo-token: '${{ secrets.GITHUB_TOKEN }}'

    - name: Process Tag Verification Result
      uses: actions/github-script@v4
      with:
        script: |
          const tagExists = '${{ steps.tag-verifier.outputs.tag-exists }}';
          const tagName = '${{ steps.get-version.outputs.version }}';

          if (tagExists === 'true') {
            core.setFailed(`The tag '${tagName}' already exists. Is the tag name correct?`);
          } else {
            core.info(`The tag '${tagName}' does not exit and is free to use!!`);
          }
