name: âœ…Unit Test PR Status Check


defaults:
  run:
    shell: pwsh


on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - preview/v*.*.*-preview.*
      - release/v*.*.*
      - master


jobs:
  unit_test_pr_status_check:
    name: Unit Test PR Status Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Restore DotNet Tools
      run: dotnet tool restore

    - name: Get Pull Request Number
      id: get-pr-number
      run: |
        $pullRequestNumber = "${{ github.ref }}".Replace("refs/pull/", "").Replace("/merge", "");
        Write-Host "Pull Request Number: $pullRequestNumber";
        Write-Host "::set-output name=pr-number::$pullRequestNumber";

    - name: Run Unit Test Status Check
      run: dotnet cicd PRUnitTestStatusCheck --pull-request-number ${{ steps.get-pr-number.outputs.pr-number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
